### ISSUE TITLE
No tocar otras carpetas ni subir archivos innecesarios de pruebas

### ISSUE THREAD

**Issue by luisespino** [tytusdb/tytus#252]
No deben hacer pull requests de archivos de ejecución de las pruebas, por ejemplo, los archivos de las bases de datos solo son para sus pruebas no para estar dentro de su carpeta en este repositorio.

También hicieron un pull request  de la carpeta __pycache__ en mi carpeta de storage/storageManagement (no deben tocar otras carpetas que no sean las asignadas a ustedes).

Favor corregir. @Oscar-Armin @theluisfer9 #251

**Comment by theluisfer9** [comment]
Una disculpa, no nos dimos cuenta que había creado esa carpeta. En el siguiente commit estará eliminada.
