### ISSUE TITLE
Utilizar solamente la carpeta asignada #48 @fraced @MarcosAlberto21

### ISSUE THREAD

**Issue by luisespino** [tytusdb/tytus#52]
@fraced @MarcosAlberto21 No hacer commit de carpetas fuera de su área de trabajo, favor utilizar solamente la carpeta asignada  https://github.com/tytusdb/tytus/tree/main/parser/team15 referente al pull request #48. No debe colocarse archivos adicionales o metadatos que generan los IDE's.

**Comment by MarcosAlberto21** [comment]
Si Inge perdone esque había una carpeta que el IDE de pycharm no estaba
mostrando esa carpeta como tal y fue mi error como coordinador no observar
eso .
Mil disculpas.
